### PR TITLE
update ubuntu package first.

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by blogic** [comment]
why is an upgrade required ? aptitude will automatically upgrade required dependencies.

**Comment by appleboy** [comment]
I create 14.04 environment using [docker file](https://github.com/appleboy/linkit-smart-7688-golang/blob/master/Dockerfile) and I will get some errors if I don't run `upgrade` command.

**Comment by blogic** [comment]
ok, that is a bug in your docker file i would guess and not the lks instructions. the upgrade effect all packages installed on your 14.04 installation and not only those required for CC. can you show us the error that this is supposed to fix ?

**Comment by appleboy** [comment]
I try to start the compilation process using docker. The following steps are docker commands.

```
$ docker pull ubuntu:14.04.3
$ docker run -ti --name test ubuntu:14.04.3 /bin/bash
```
then run the step 1 to install dependency packages.

```
$ apt-get install git g++ make libncurses5-dev subversion libssl-dev gawk libxml-parser-perl unzip wget python xz-utils
```

got the following errors

screen shot 2016-04-17 at 11 51 18 pm

How to fix? Run the following command to update all packages first.

```
$ apt-get update && apt-get upgrade
```

Thanks

**Comment by blogic** [comment]
apt-get update should be enough. calling upgrade will upgrade unrelated packages and cause side effects. please retry with only the update call.

**Comment by appleboy** [comment]
@blogic You are right. I updated commit.

**Comment by appleboy** [comment]
@blogic any updates?

**Comment by blogic** [comment]
not yet, i need to rebase your patches to fold them into one and i was busy testing a wifi driver update.

**Comment by appleboy** [comment]
@blogic I got it. Thanks for your contribution.

**Pull request closed without merging**
